import React,{useState,useEffect} from 'react';
import { ArrowRight,ArrowLeft,ArrowUpRight,Sparkles,Plus,Check,CheckCircle2,Search,SlidersHorizontal,Layers3,LayoutGrid,ChevronDown,Send,BriefcaseBusiness,GraduationCap,Clock3,Target,Lightbulb,Database,ShieldCheck,ExternalLink,RotateCcw } from 'lucide-react';
import {initialTasks,fields,breakdown,rating,readiness,readinessLabel,calculateMockRating,mockCard,mockTask,fallbackQuestions} from './data.js';
import {apiErrorMessage} from './api/client.js';
import {createTask,getTask,listTasks,updateTask,getTaskRating,confirmTask,publishTask} from './api/tasks.js';
import {getQuestions,generateCard} from './api/ai.js';
import {createProposal,getProposals,updateProposalStatus} from './api/proposals.js';

const KEY='alem-demo-v1';
function stored(){try {const v=JSON.parse(localStorage.getItem(KEY));return v&&Array.isArray(v.tasks)&&Array.isArray(v.proposals)?v:null} catch{return null}}
function Badge({score,level}){const current=level||readiness(score);return <span className={'badge '+String(current).toLowerCase()}><span className="badge-dot"/>{readinessLabel(current)}</span>}
function Logo({onClick}){return <button className="logo" onClick={onClick} aria-label="Alem home"><span className="logo-mark"><Layers3 size={22} strokeWidth={2.7}/></span><span>alem<span className="logo-period">.</span></span></button>}
function RatingPanel({task,ratingInfo}){const local=calculateMockRating(task);const details=ratingInfo||local;const score=Number(details.score??rating(task));const level=details.level||task.readiness_level||readiness(score);const missing=details.missing||local.missing;return <aside className="rating-panel"><div className="panel-eyebrow"><Sparkles size={15}/> TASK READINESS</div><div className="score-line"><strong>{score}</strong><span>/ 100</span><Badge score={score} level={level}/></div><div className="progress"><span style={{width:`${score}%`}}/></div><p className="muted small">A clearer brief makes it easier for great teams to respond.</p><div className="panel-divider"/><div className="panel-heading">Score breakdown</div><div className="breakdown">{breakdown.map(([label,points,key])=><div className="breakdown-row" key={label}><span>{label}</span><strong>{details.breakdown?.[key]??0} <small>/ {points}</small></strong></div>)}</div><div className="panel-divider"/><div className="panel-heading"><Lightbulb size={16}/> Missing information</div>{missing.length?<div className="suggestions">{missing.slice(0,5).map(key=><div key={key} className="suggestion"><span>+</span> Add {key.replaceAll('_',' ')}</div>)}</div>:<div className="complete"><CheckCircle2 size={18}/> Your brief covers every scoring category.</div>}</aside>}
function App(){const useMock=import.meta.env.VITE_USE_MOCK==='true';const [saved]=useState(()=>useMock?stored():null);const [tasks,setTasks]=useState(saved?.tasks||(useMock?initialTasks:[]));const [proposals,setProposals]=useState(saved?.proposals||[]);const [mode,setMode]=useState('business');const [page,setPage]=useState('home');const [selected,setSelected]=useState(null);const [step,setStep]=useState(0);const [description,setDescription]=useState('');const [createTopic,setCreateTopic]=useState('');const [answers,setAnswers]=useState(['','','']);const [questionList,setQuestionList]=useState(fallbackQuestions);const [draft,setDraft]=useState(null);const [ratingInfo,setRatingInfo]=useState(null);const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(!useMock);const [topic,setTopic]=useState('All topics');const [level,setLevel]=useState('All levels');const [sort,setSort]=useState('Highest rated');const [proposalForm,setProposalForm]=useState({team_id:String(import.meta.env.VITE_DEMO_TEAM_ID||1),idea:'',plan:'',deadline:'',prototype_url:''});const [notice,setNotice]=useState('');
  useEffect(()=>{if(useMock)localStorage.setItem(KEY,JSON.stringify({tasks,proposals}))},[useMock,tasks,proposals]);
  useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),3600);return()=>clearTimeout(t)},[notice]);
  const navigate=(target,id)=>{setPage(target);setSelected(id||null);window.scrollTo({top:0,behavior:'smooth'})};
  const isPublished=item=>Boolean(item?.published||item?.status==='published');
  const isConfirmed=item=>Boolean(item?.confirmed||item?.status==='confirmed');
  const task=tasks.find(t=>String(t.id)===String(selected));
  const replaceTask=next=>setTasks(old=>old.some(item=>String(item.id)===String(next.id))?old.map(item=>String(item.id)===String(next.id)?next:item):[next,...old]);
  const editDraft=next=>{setDraft(next);if(useMock)replaceTask(next)};
  const showError=error=>setNotice(apiErrorMessage(error));
  const refreshCatalog=async()=>{if(useMock)return;setLoading(true);try{const result=await listTasks({topic:topic==='All topics'?'':topic,level:level==='All levels'?'':level.toLowerCase(),sort:sort==='Highest rated'?'rating':''});const next=sort==='Lowest rated'?[...(result||[])].reverse():(result||[]);setTasks(next)}catch(error){showError(error)}finally{setLoading(false)}};
  useEffect(()=>{if(!useMock&&(page==='home'||page==='catalog'))refreshCatalog()},[useMock,page,topic,level,sort]);
  useEffect(()=>{if(useMock||!selected||!['details','proposals'].includes(page))return;getTask(selected).then(replaceTask).catch(showError)},[useMock,page,selected]);
  useEffect(()=>{if(useMock||page!=='proposals'||!selected)return;getProposals(selected).then(setProposals).catch(showError)},[useMock,page,selected]);
  const begin=()=>{setDescription('');setCreateTopic('');setAnswers(['','','']);setQuestionList(fallbackQuestions);setDraft(null);setRatingInfo(null);setStep(0);navigate('create')};
  const analyze=async()=>{if(description.trim().length<10){setNotice('Add a little more detail to your task.');return}setBusy(true);try{let created;if(useMock){created=mockTask(description,createTopic)}else{created=await createTask({initial_description:description.trim(),topic:createTopic.trim()});replaceTask(created)}setDraft(created);setRatingInfo(useMock?calculateMockRating(created):{score:created.rating,level:created.readiness_level});if(useMock){setQuestionList(fallbackQuestions)}else{try{const result=await getQuestions(description.trim());const next=result?.questions?.filter(Boolean).slice(0,3);setQuestionList(next?.length>=3?next:fallbackQuestions);if(!next?.length)setNotice('AI questions are unavailable; using demo questions.')}catch(error){setQuestionList(fallbackQuestions);setNotice(`AI questions are unavailable; using demo questions. ${apiErrorMessage(error)}`)}}setStep(1)}catch(error){showError(error)}finally{setBusy(false)}};
  const generate=async()=>{if(questionList.some((_,i)=>!answers[i]?.trim())){setNotice('Answer all three questions to continue.');return}if(!draft){setNotice('Create the task draft first.');return}setBusy(true);try{const card=useMock?mockCard(description,questionList.map((question,i)=>({question,answer:answers[i]}))):await generateCard(description.trim(),questionList.map((question,i)=>({question,answer:answers[i]})));const next={...draft,...card};setDraft(next);setRatingInfo(useMock?calculateMockRating(next):null);setStep(2)}catch(error){showError(error)}finally{setBusy(false)}};
  const persistDraft=async()=>{if(!draft)return null;if(useMock){const next={...draft,updated_at:new Date().toISOString()};const score=calculateMockRating(next);const savedDraft={...next,...score,rating:score.score,readiness_level:score.level};replaceTask(savedDraft);setDraft(savedDraft);setRatingInfo(score);return savedDraft}const savedDraft=await updateTask(draft.id,draft);replaceTask(savedDraft);setDraft(savedDraft);const details=await getTaskRating(savedDraft.id);setRatingInfo(details);return savedDraft};
  const saveDraft=async()=>{setBusy(true);try{await persistDraft();setNotice('Changes saved to the backend.')}catch(error){showError(error)}finally{setBusy(false)}};
  const confirmDraft=async()=>{if(!draft?.title?.trim()){setNotice('Add a task title before confirming.');return}setBusy(true);try{const savedDraft=await persistDraft();const confirmed=useMock?{...savedDraft,confirmed:true}:await confirmTask(savedDraft.id);replaceTask(confirmed);setDraft(confirmed);setNotice('Task confirmed. Ready to publish.')}catch(error){showError(error)}finally{setBusy(false)}};
  const publish=async()=>{if(!draft?.title?.trim()){setNotice('Add a task title before publishing.');return}if(!isConfirmed(draft)){setNotice('Confirm the task before publishing.');return}setBusy(true);try{const published=useMock?{...draft,published:true}:await publishTask(draft.id);replaceTask(published);setDraft(published);setNotice('Your task is live in the catalog.');navigate('catalog')}catch(error){showError(error)}finally{setBusy(false)}};
  const list=useMock?tasks.filter(isPublished).filter(t=>topic==='All topics'||t.topic===topic).filter(t=>level==='All levels'||readiness(rating(t))===level.toLowerCase()).sort((a,b)=>sort==='Highest rated'?rating(b)-rating(a):rating(a)-rating(b)):tasks;
  const topics=['All topics',...new Set(tasks.filter(isPublished).map(t=>t.topic).filter(Boolean))];
  const submitProposal=async e=>{e.preventDefault();if(!task)return;setBusy(true);try{const payload={team_id:Number(proposalForm.team_id),idea:proposalForm.idea,plan:proposalForm.plan,deadline:proposalForm.deadline,prototype_url:proposalForm.prototype_url};const created=useMock?{...payload,id:crypto.randomUUID(),task_id:task.id,status:'pending',created_at:new Date().toISOString(),updated_at:new Date().toISOString()}:await createProposal(task.id,payload);setProposals(old=>[created,...old]);setProposalForm({team_id:String(import.meta.env.VITE_DEMO_TEAM_ID||1),idea:'',plan:'',deadline:'',prototype_url:''});setNotice('Proposal submitted successfully.');navigate('details',task.id)}catch(error){showError(error)}finally{setBusy(false)}};
  const changeStatus=async(id,status)=>{try{const updated=useMock?{...proposals.find(item=>item.id===id),status}:await updateProposalStatus(id,status);setProposals(old=>old.map(item=>item.id===id?{...item,...updated,status}:item));setNotice(`Proposal ${status}.`)}catch(error){showError(error)}};
  return <div className="app"><div className="background-glow"/><header className="site-header"><div className="header-inner"><Logo onClick={()=>navigate('home')}/><nav className="main-nav" aria-label="Main navigation"><button className={page==='home'?'nav-active':''} onClick={()=>navigate('home')}>Overview</button><button className={page==='catalog'?'nav-active':''} onClick={()=>navigate('catalog')}>Explore tasks</button>{mode==='business'&&<button className={page==='create'?'nav-active':''} onClick={begin}>Create task</button>}</nav><div className="header-actions"><div className="mode-switch" aria-label="User mode"><button className={mode==='business'?'active':''} onClick={()=>setMode('business')}><BriefcaseBusiness size={15}/> Business</button><button className={mode==='student'?'active':''} onClick={()=>setMode('student')}><GraduationCap size={15}/> Student</button></div><button className="avatar" aria-label="Demo account">A</button></div></div></header>
  {page==='home'&&<main className="home container enter"><div className="hero"><div className="hero-copy"><span className="eyebrow"><span className="live-dot"/> THE BRIDGE BETWEEN BUSINESS & TALENT</span><h1>Big ideas start<br/>with <em>a clear challenge.</em></h1><p>Turn real business needs into meaningful opportunities for the next generation of builders.</p><div className="hero-actions"><button className="button primary" onClick={begin}>Create a challenge <ArrowUpRight size={18}/></button><button className="button subtle" onClick={()=>navigate('catalog')}>Explore opportunities <ArrowRight size={17}/></button></div><div className="hero-foot"><div className="stacked-avatars"><span>AK</span><span>DM</span><span>ST</span></div><div><strong>Where potential meets purpose</strong><small>Built for businesses and student teams</small></div></div></div><div className="hero-visual"><div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/><div className="floating-chip chip-top"><Sparkles size={16}/> AI-assisted task builder</div><div className="preview-card"><div className="preview-top"><span className="preview-icon"><Target size={23}/></span><span className="preview-kicker">FEATURED CHALLENGE</span><ArrowUpRight size={17}/></div><h3>Make warehouse operations smarter</h3><p>Help a growing retailer predict demand and stay ahead of stock shortages.</p><div className="preview-rule"/><div className="preview-bottom"><Badge score={95}/><span><strong>95</strong> / 100</span></div></div><div className="floating-chip chip-bottom"><span className="chip-check"><Check size={14}/></span> Ready for great ideas</div></div></div><div className="home-bottom"><div className="section-head"><div><span className="overline">EXPLORE WHAT'S POSSIBLE</span><h2>Real problems. Real impact.</h2></div><button className="text-link" onClick={()=>navigate('catalog')}>View all challenges <ArrowRight size={17}/></button></div><div className="featured-grid">{tasks.filter(isPublished).slice(0,3).map(t=><TaskTile key={t.id} task={t} open={()=>navigate('details',t.id)}/>)}</div></div></main>}
  {page==='catalog'&&<main className="container page enter"><div className="page-title-row"><div><span className="overline">THE OPPORTUNITY BOARD</span><h1>Explore challenges<span className="accent-dot">.</span></h1><p>Find a real-world problem worth solving.</p></div>{mode==='business'&&<button className="button primary" onClick={begin}><Plus size={18}/> Create task</button>}</div><div className="catalog-toolbar"><div className="toolbar-label"><LayoutGrid size={18}/> {loading?'Loading...':`${list.length} challenges`}</div><div className="filter-group"><label><SlidersHorizontal size={16}/><select value={topic} onChange={e=>setTopic(e.target.value)} aria-label="Filter by topic">{topics.map(v=><option key={v}>{v}</option>)}</select><ChevronDown size={14}/></label><label><select value={level} onChange={e=>setLevel(e.target.value)} aria-label="Filter by readiness">{['All levels','Draft','Working','Ready','Priority'].map(v=><option key={v}>{v}</option>)}</select><ChevronDown size={14}/></label><label><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort by rating">{['Highest rated','Lowest rated'].map(v=><option key={v}>{v}</option>)}</select><ChevronDown size={14}/></label></div></div>{loading?<div className="empty"><Search size={32}/><h3>Loading challenges</h3><p>Connecting to the backend catalog.</p></div>:list.length?<div className="catalog-grid">{list.map(t=><TaskTile key={t.id} task={t} open={()=>navigate('details',t.id)}/>)}</div>:<div className="empty"><Search size={32}/><h3>No tasks found</h3><p>Try a different topic or readiness filter.</p><button className="button subtle" onClick={()=>{setTopic('All topics');setLevel('All levels')}}>Clear filters</button></div>}</main>}
  {page==='create'&&<main className="container page enter"><div className="back-link"><button onClick={()=>navigate('home')}><ArrowLeft size={16}/> Back to overview</button></div><div className="builder-heading"><div><span className="overline">BUSINESS WORKSPACE</span><h1>Create a challenge<span className="accent-dot">.</span></h1><p>Start with what you know. We'll help you shape the rest.</p></div><div className="stepper"><span className={step>=0?'step-active':''}>01 <b>Describe</b></span><i/><span className={step>=1?'step-active':''}>02 <b>Clarify</b></span><i/><span className={step>=2?'step-active':''}>03 <b>Refine</b></span></div></div>
    {step===0&&<div className="builder-start"><div className="form-surface"><div className="surface-icon"><Sparkles size={21}/></div><h2>What challenge are you facing?</h2><p>Write it in your own words. It doesn't need to be perfect.</p><label className="field-label" htmlFor="description">YOUR INITIAL DESCRIPTION</label><textarea id="description" className="input big-input" value={description} onChange={e=>setDescription(e.target.value)} placeholder="For example: We need a better way to manage our warehouse and keep track of inventory..."/><label className="field-label" htmlFor="create-topic">TOPIC <small>(optional)</small></label><input id="create-topic" className="input" value={createTopic} onChange={e=>setCreateTopic(e.target.value)} placeholder="e.g. logistics"/><div className="form-bottom"><span><ShieldCheck size={16}/> Your draft is private until you publish</span><button className="button primary" disabled={busy} onClick={analyze}>{busy?'Analyzing...':'Analyze task'} <ArrowRight size={18}/></button></div></div><div className="helper-surface"><div className="helper-symbol"><Lightbulb size={21}/></div><h3>Good challenges start simple.</h3><p>Describe the problem you see in your business. Our guided flow helps you fill the gaps and make it actionable for students.</p><div className="helper-line"><CheckCircle2 size={16}/> No technical brief needed</div><div className="helper-line"><CheckCircle2 size={16}/> Takes about 2 minutes</div></div></div>}
    {step===1&&<div className="questions-layout"><div className="form-surface"><div className="surface-icon"><Sparkles size={21}/></div><h2>Let's make it clearer.</h2><p>Answer three quick questions to turn your idea into a useful brief.</p>{questionList.map((q,i)=><label key={q} className="question-block"><span className="question-number">0{i+1}</span><strong>{q}</strong><textarea className="input" value={answers[i]} onChange={e=>setAnswers(old=>old.map((v,j)=>j===i?e.target.value:v))} placeholder={['e.g. Warehouse managers and inventory staff','e.g. Sales history and current stock spreadsheets','e.g. Reduce stockouts by 20%'][i]}/></label>)}<div className="form-bottom"><button className="button subtle" onClick={()=>setStep(0)}><ArrowLeft size={17}/> Back</button><button className="button primary" disabled={busy} onClick={generate}>{busy?'Generating card...':'Generate task card'} <Sparkles size={17}/></button></div></div><div className="quote-card"><span className="overline">YOUR STARTING POINT</span><p>“{description}”</p><span className="quote-footer"><Sparkles size={16}/> Turning ideas into action</span></div></div>}
    {step===2&&draft&&<div className="editor-layout"><div className="editor-column"><div className="editor-intro"><span className="eyebrow"><Sparkles size={15}/> YOUR CHALLENGE, REFINED</span><h2>Make it yours.</h2><p>Every detail helps a student team understand what success looks like.</p></div><div className="editor-card"><div className="editor-card-top"><div className="surface-icon"><Layers3 size={21}/></div><div><h3>Task details</h3><p>Save to recalculate the backend rating.</p></div><Badge score={ratingInfo?.score??rating(draft)} level={ratingInfo?.level||draft.readiness_level}/></div><div className="editor-fields">{fields.map(([key,label,kind])=><label key={key} className={kind==='textarea'?'field full':'field'}><span>{label}</span>{kind==='textarea'?<textarea className="input" value={draft[key]||''} onChange={e=>editDraft({...draft,[key]:e.target.value})} placeholder={`Add ${label.toLowerCase()}...`}/>:<input className="input" value={draft[key]||''} onChange={e=>editDraft({...draft,[key]:e.target.value})} placeholder={`Add ${label.toLowerCase()}...`}/>}</label>)}</div><div className="editor-actions"><button className="button subtle" disabled={busy} onClick={saveDraft}>{busy?'Saving...':'Save changes'}</button><div>{isConfirmed(draft)?<span className="confirmed-label"><CheckCircle2 size={17}/> Confirmed</span>:<button className="button outline" disabled={busy} onClick={confirmDraft}><Check size={17}/> Confirm</button>}<button className="button primary" disabled={busy} onClick={publish}>Publish task <ArrowUpRight size={17}/></button></div></div></div></div><RatingPanel task={draft} ratingInfo={ratingInfo}/></div>}
  </main>}
  {page==='details'&&task&&<main className="container page enter"><div className="back-link"><button onClick={()=>navigate('catalog')}><ArrowLeft size={16}/> All challenges</button></div><div className="detail-header"><div><div className="detail-meta"><span className="topic-pill">{task.topic}</span><Badge score={rating(task)}/></div><h1>{task.title}</h1><p>{task.need||task.context||'A new challenge waiting for great ideas.'}</p></div><div className="detail-score"><strong>{rating(task)}</strong><span>/100</span><small>READINESS SCORE</small></div></div><div className="details-layout"><article className="detail-content"><div className="detail-content-head"><span className="surface-icon"><Layers3 size={20}/></span><div><h2>The challenge</h2><p>Everything you need to know before getting started.</p></div></div>{fields.filter(([key])=>key!=='title'&&key!=='topic').map(([key,label])=><div className="detail-section" key={key}><h3>{label}</h3><p>{task[key]||'Not provided yet.'}</p></div>)}</article><aside className="detail-side"><div className="side-card"><div className="side-icon"><Target size={22}/></div><h3>Ready to build something meaningful?</h3><p>Bring your perspective and show this business what your team can do.</p>{mode==='student'?<button className="button primary full-button" onClick={()=>navigate('proposal',task.id)}>Submit a proposal <ArrowRight size={17}/></button>:<button className="button primary full-button" onClick={()=>navigate('proposals',task.id)}>View proposals <ArrowRight size={17}/></button>}</div><div className="side-note"><ShieldCheck size={17}/> Real challenges from real businesses.</div></aside></div></main>}
  {page==='proposal'&&task&&<main className="container page enter narrow"><div className="back-link"><button onClick={()=>navigate('details',task.id)}><ArrowLeft size={16}/> Back to challenge</button></div><span className="overline">YOUR PROPOSAL</span><h1>Bring your idea to life<span className="accent-dot">.</span></h1><p className="page-lead">Applying to <strong>{task.title}</strong>. Tell the business how your team would tackle it.</p><form className="form-surface proposal-form" onSubmit={submitProposal}><label className="field"><span>Team ID</span><input className="input" required type="number" min="1" value={proposalForm.team_id} onChange={e=>setProposalForm({...proposalForm,team_id:e.target.value})} placeholder="Seeded demo team ID"/></label><label className="field"><span>Your idea</span><textarea className="input" required value={proposalForm.idea} onChange={e=>setProposalForm({...proposalForm,idea:e.target.value})} placeholder="What's your proposed solution?"/></label><label className="field"><span>Plan of action</span><textarea className="input" required value={proposalForm.plan} onChange={e=>setProposalForm({...proposalForm,plan:e.target.value})} placeholder="What steps will you take?"/></label><div className="form-pair"><label className="field"><span>Expected deadline</span><input className="input" type="date" required value={proposalForm.deadline} onChange={e=>setProposalForm({...proposalForm,deadline:e.target.value})}/></label><label className="field"><span>Prototype link</span><input className="input" type="url" required value={proposalForm.prototype_url} onChange={e=>setProposalForm({...proposalForm,prototype_url:e.target.value})} placeholder="https://..."/></label></div><div className="form-bottom"><span><ShieldCheck size={16}/> Backend requires all proposal fields.</span><button className="button primary" disabled={busy} type="submit">Submit proposal <Send size={17}/></button></div></form></main>}
  {page==='proposals'&&task&&<main className="container page enter"><div className="back-link"><button onClick={()=>navigate('details',task.id)}><ArrowLeft size={16}/> Back to challenge</button></div><span className="overline">BUSINESS WORKSPACE</span><h1>Team proposals<span className="accent-dot">.</span></h1><p className="page-lead">Review ideas for <strong>{task.title}</strong>.</p>{proposals.filter(p=>String(p.task_id)===String(task.id)).length?proposals.filter(p=>String(p.task_id)===String(task.id)).map(p=><article className="proposal-card" key={p.id}><div className="proposal-top"><div className="team-icon"><GraduationCap size={21}/></div><div><span className="overline">STUDENT TEAM</span><h2>Team #{p.team_id}</h2></div><span className={'status '+p.status}>{p.status}</span></div><div className="proposal-body"><div><h3>The idea</h3><p>{p.idea}</p></div><div><h3>Action plan</h3><p>{p.plan}</p></div></div><div className="proposal-foot"><span><Clock3 size={16}/> {p.deadline}</span>{p.prototype_url&&<a href={p.prototype_url} target="_blank" rel="noreferrer">View prototype <ExternalLink size={15}/></a>}<div className="proposal-actions"><button className="button outline" onClick={()=>changeStatus(p.id,'rejected')} disabled={p.status!=='pending'}>Reject</button><button className="button primary" onClick={()=>changeStatus(p.id,'accepted')} disabled={p.status!=='pending'}><Check size={16}/> Accept</button></div></div></article>):<div className="empty"><GraduationCap size={32}/><h3>No proposals yet</h3><p>Once student teams apply, you'll find their ideas here.</p><button className="button subtle" onClick={()=>navigate('catalog')}>Explore tasks <ArrowRight size={16}/></button></div>}</main>}
  <footer className="footer container"><Logo onClick={()=>navigate('home')}/><span>Ideas into impact. © 2026 Alem.</span><button onClick={()=>navigate('catalog')}>Explore challenges <ArrowUpRight size={15}/></button></footer>{notice&&<div className="toast" role="status"><CheckCircle2 size={18}/>{notice}</div>}</div>
}
function TaskTile({task,open}){const score=rating(task);return <button className="task-tile" onClick={open}><div className="tile-top"><span className="topic-pill">{task.topic}</span><ArrowUpRight className="tile-arrow" size={19}/></div><div className="tile-body"><h3>{task.title}</h3><p>{task.need||task.context||'A fresh challenge looking for a student team.'}</p></div><div className="tile-bottom"><Badge score={score}/><span className="tile-score"><strong>{score}</strong><small>/100</small></span></div><div className="tile-progress"><span style={{width:`${score}%`}}/></div></button>}
export default App;
