import React,{useState,useEffect} from 'react';
import { ArrowRight,ArrowLeft,ArrowUpRight,Sparkles,Plus,Check,CheckCircle2,Search,SlidersHorizontal,Layers3,LayoutGrid,ChevronDown,Send,BriefcaseBusiness,GraduationCap,Clock3,Target,Lightbulb,Database,ShieldCheck,ExternalLink,RotateCcw } from 'lucide-react';
import {initialTasks,fields,breakdown,rating,readiness,readinessLabel,topicLabel,fieldLabel,proposalStatusLabel,calculateMockRating,mockCard,mockTask,fallbackQuestions} from './data.js';
import {apiErrorMessage} from './api/client.js';
import {createTask,getTask,listTasks,updateTask,getTaskRating,confirmTask,publishTask} from './api/tasks.js';
import {getQuestions,generateCard} from './api/ai.js';
import {createProposal,getProposals,updateProposalStatus} from './api/proposals.js';

const KEY='alem-demo-v1';
function stored(){try {const v=JSON.parse(localStorage.getItem(KEY));return v&&Array.isArray(v.tasks)&&Array.isArray(v.proposals)?v:null} catch{return null}}
function Badge({score,level}){const current=level||readiness(score);return <span className={'badge '+String(current).toLowerCase()}><span className="badge-dot"/>{readinessLabel(current)}</span>}
function readinessFilterLabel(value){return value==='All levels'?'Все уровни':readinessLabel(value)}
function aiModeLabel(mode){return mode==='fallback'?'Резервный режим ИИ':'Живой режим ИИ'}
function Logo({onClick}){return <button className="logo" onClick={onClick} aria-label="Главная Alem"><span className="logo-mark"><Layers3 size={22} strokeWidth={2.7}/></span><span>alem<span className="logo-period">.</span></span></button>}
function RatingPanel({task,ratingInfo,useMock}){const local=useMock?calculateMockRating(task):null;const details=ratingInfo||local||{score:Number(task?.rating||0),level:task?.readiness_level||'draft',breakdown:null,missing:null};const score=Number(details.score??task?.rating??0);const level=details.level||task?.readiness_level||'draft';const hasDetails=Boolean(details.breakdown&&Array.isArray(details.missing));return <aside className="rating-panel"><div className="panel-eyebrow"><Sparkles size={15}/> ГОТОВНОСТЬ ЗАДАЧИ</div><div className="score-line"><strong>{score}</strong><span>/ 100</span><Badge score={score} level={level}/></div><div className="progress"><span style={{width:`${score}%`}}/></div><p className="muted small">Понятное описание помогает сильным командам предложить решение.</p><div className="panel-divider"/><div className="panel-heading">Разбор рейтинга</div>{hasDetails?<div className="breakdown">{breakdown.map(([label,points,key])=><div className="breakdown-row" key={label}><span>{label}</span><strong>{details.breakdown[key]??0} <small>/ {points}</small></strong></div>)}</div>:<div className="muted small">Сохраните изменения, чтобы получить актуальный расчёт рейтинга.</div>}{hasDetails&&<><div className="panel-divider"/><div className="panel-heading"><Lightbulb size={16}/> Недостающие сведения</div>{details.missing.length?<div className="suggestions">{details.missing.slice(0,5).map(key=><div key={key} className="suggestion"><span>+</span> {fieldLabel(key)}</div>)}</div>:<div className="complete"><CheckCircle2 size={18}/> В описании заполнены все категории оценки.</div>}</>}</aside>}
function App(){const useMock=import.meta.env.VITE_USE_MOCK==='true';const [saved]=useState(()=>useMock?stored():null);const [tasks,setTasks]=useState(saved?.tasks||(useMock?initialTasks:[]));const [proposals,setProposals]=useState(saved?.proposals||[]);const [mode,setMode]=useState('business');const [page,setPage]=useState('home');const [selected,setSelected]=useState(null);const [step,setStep]=useState(0);const [description,setDescription]=useState('');const [createTopic,setCreateTopic]=useState('');const [answers,setAnswers]=useState(['','','']);const [questionList,setQuestionList]=useState(fallbackQuestions);const [aiMode,setAiMode]=useState('');const [draft,setDraft]=useState(null);const [ratingInfo,setRatingInfo]=useState(null);const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(!useMock);const [topic,setTopic]=useState('All topics');const [level,setLevel]=useState('All levels');const [sort,setSort]=useState('Highest rated');const [proposalForm,setProposalForm]=useState({team_id:String(import.meta.env.VITE_DEMO_TEAM_ID||1),idea:'',plan:'',deadline:'',prototype_url:''});const [notice,setNotice]=useState('');
  useEffect(()=>{if(useMock)localStorage.setItem(KEY,JSON.stringify({tasks,proposals}))},[useMock,tasks,proposals]);
  useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),3600);return()=>clearTimeout(t)},[notice]);
  const navigate=(target,id)=>{setPage(target);setSelected(id||null);window.scrollTo({top:0,behavior:'smooth'})};
  const isPublished=item=>Boolean(item?.published||item?.status==='published');
  const isConfirmed=item=>Boolean(item?.confirmed||item?.status==='confirmed');
  const task=tasks.find(t=>String(t.id)===String(selected));
  const replaceTask=next=>setTasks(old=>old.some(item=>String(item.id)===String(next.id))?old.map(item=>String(item.id)===String(next.id)?next:item):[next,...old]);
  const editDraft=next=>{setDraft(next);if(useMock)replaceTask(next)};
  const showError=error=>setNotice(apiErrorMessage(error));
  const refreshCatalog=async()=>{if(useMock)return;setLoading(true);try{const result=await listTasks({topic:topic==='All topics'?'':topic,level:level==='All levels'?'':level.toLowerCase(),sort:sort?'rating':''});const next=sort==='Lowest rated'?[...(result||[])].reverse():(result||[]);setTasks(next)}catch(error){showError(error)}finally{setLoading(false)}};
  useEffect(()=>{if(!useMock&&(page==='home'||page==='catalog'))refreshCatalog()},[useMock,page,topic,level,sort]);
  useEffect(()=>{if(useMock||!selected||!['details','proposals'].includes(page))return;getTask(selected).then(replaceTask).catch(showError)},[useMock,page,selected]);
  useEffect(()=>{if(useMock||page!=='proposals'||!selected)return;getProposals(selected).then(setProposals).catch(showError)},[useMock,page,selected]);
  const begin=()=>{setDescription('');setCreateTopic('');setAnswers(['','','']);setQuestionList(fallbackQuestions);setDraft(null);setRatingInfo(null);setAiMode('');setStep(0);navigate('create')};
  const analyze=async()=>{if(description.trim().length<10){setNotice('Добавьте немного больше деталей в задачу.');return}setBusy(true);try{let created;if(useMock){created=mockTask(description,createTopic);setAiMode('fallback')}else{created=await createTask({initial_description:description.trim(),topic:createTopic.trim()});replaceTask(created);setAiMode('')}setDraft(created);setRatingInfo(useMock?calculateMockRating(created):{score:created.rating,level:created.readiness_level});if(useMock){setQuestionList(fallbackQuestions)}else{try{const result=await getQuestions(description.trim());setAiMode(result.mode||'');const next=result.data?.questions?.filter(Boolean).slice(0,3);setQuestionList(next?.length>=3?next:fallbackQuestions);if(!next?.length)setNotice('Вопросы ИИ недоступны, используем демонстрационные вопросы.')}catch(error){setAiMode('fallback');setQuestionList(fallbackQuestions);setNotice(`Вопросы ИИ недоступны, используем демонстрационные вопросы. ${apiErrorMessage(error)}`)}}setStep(1)}catch(error){showError(error)}finally{setBusy(false)}};
  const generate=async()=>{if(questionList.some((_,i)=>!answers[i]?.trim())){setNotice('Ответьте на все три вопроса, чтобы продолжить.');return}if(!draft){setNotice('Сначала создайте черновик задачи.');return}setBusy(true);try{const result=useMock?{data:mockCard(description,questionList.map((question,i)=>({question,answer:answers[i]}))),mode:'fallback'}:await generateCard(description.trim(),questionList.map((question,i)=>({question,answer:answers[i]})));const next={...draft,...result.data};setDraft(next);setAiMode(result.mode||aiMode);setRatingInfo(useMock?calculateMockRating(next):null);setStep(2)}catch(error){showError(error)}finally{setBusy(false)}};
  const persistDraft=async()=>{if(!draft)return null;if(useMock){const next={...draft,updated_at:new Date().toISOString()};const score=calculateMockRating(next);const savedDraft={...next,...score,rating:score.score,readiness_level:score.level};replaceTask(savedDraft);setDraft(savedDraft);setRatingInfo(score);return savedDraft}const savedDraft=await updateTask(draft.id,draft);replaceTask(savedDraft);setDraft(savedDraft);const details=await getTaskRating(savedDraft.id);setRatingInfo(details);return savedDraft};
  const saveDraft=async()=>{setBusy(true);try{await persistDraft();setNotice('Изменения сохранены.')}catch(error){showError(error)}finally{setBusy(false)}};
  const confirmDraft=async()=>{if(!draft?.title?.trim()){setNotice('Добавьте название задачи перед подтверждением.');return}setBusy(true);try{const savedDraft=await persistDraft();const confirmed=useMock?{...savedDraft,confirmed:true}:await confirmTask(savedDraft.id);replaceTask(confirmed);setDraft(confirmed);setNotice('Задача подтверждена и готова к публикации.')}catch(error){showError(error)}finally{setBusy(false)}};
  const publish=async()=>{if(!draft?.title?.trim()){setNotice('Добавьте название задачи перед публикацией.');return}if(!isConfirmed(draft)){setNotice('Подтвердите задачу перед публикацией.');return}setBusy(true);try{const published=useMock?{...draft,published:true}:await publishTask(draft.id);replaceTask(published);setDraft(published);setNotice('Задача опубликована в каталоге.');navigate('catalog')}catch(error){showError(error)}finally{setBusy(false)}};
  const list=useMock?tasks.filter(isPublished).filter(t=>topic==='All topics'||t.topic===topic).filter(t=>level==='All levels'||readiness(rating(t))===level.toLowerCase()).sort((a,b)=>sort==='Highest rated'?rating(b)-rating(a):rating(a)-rating(b)):tasks;
  const topics=['All topics',...new Set(tasks.filter(isPublished).map(t=>t.topic).filter(Boolean))];
  const submitProposal=async e=>{e.preventDefault();if(!task)return;setBusy(true);try{const payload={team_id:Number(proposalForm.team_id),idea:proposalForm.idea,plan:proposalForm.plan,deadline:proposalForm.deadline,prototype_url:proposalForm.prototype_url};const created=useMock?{...payload,id:crypto.randomUUID(),task_id:task.id,status:'pending',created_at:new Date().toISOString(),updated_at:new Date().toISOString()}:await createProposal(task.id,payload);setProposals(old=>[created,...old]);setProposalForm({team_id:String(import.meta.env.VITE_DEMO_TEAM_ID||1),idea:'',plan:'',deadline:'',prototype_url:''});setNotice('Предложение успешно отправлено.');navigate('details',task.id)}catch(error){showError(error)}finally{setBusy(false)}};
  const changeStatus=async(id,status)=>{try{const updated=useMock?{...proposals.find(item=>item.id===id),status}:await updateProposalStatus(id,status);setProposals(old=>old.map(item=>item.id===id?{...item,...updated,status}:item));setNotice(`Статус предложения: ${proposalStatusLabel(status)}.`)}catch(error){showError(error)}};
  return <div className="app"><div className="background-glow"/><header className="site-header"><div className="header-inner"><Logo onClick={()=>navigate('home')}/><nav className="main-nav" aria-label="Основная навигация"><button className={page==='home'?'nav-active':''} onClick={()=>navigate('home')}>Обзор</button><button className={page==='catalog'?'nav-active':''} onClick={()=>navigate('catalog')}>Каталог задач</button>{mode==='business'&&<button className={page==='create'?'nav-active':''} onClick={begin}>Создать задачу</button>}</nav><div className="header-actions"><div className="mode-switch" aria-label="Режим пользователя"><button className={mode==='business'?'active':''} onClick={()=>setMode('business')}><BriefcaseBusiness size={15}/> Бизнес</button><button className={mode==='student'?'active':''} onClick={()=>setMode('student')}><GraduationCap size={15}/> Студент</button></div><button className="avatar" aria-label="Демонстрационный аккаунт">A</button></div></div></header>
  {page==='home'&&<main className="home container enter"><div className="hero"><div className="hero-copy"><span className="eyebrow"><span className="live-dot"/> МОСТ МЕЖДУ БИЗНЕСОМ И ТАЛАНТАМИ</span><h1>Большие идеи начинаются<br/>с <em>понятной задачей.</em></h1><p>Превращайте реальные потребности бизнеса в полезные возможности для нового поколения создателей.</p><div className="hero-actions"><button className="button primary" onClick={begin}>Создать задачу <ArrowUpRight size={18}/></button><button className="button subtle" onClick={()=>navigate('catalog')}>Найти возможности <ArrowRight size={17}/></button></div><div className="hero-foot"><div className="stacked-avatars"><span>AK</span><span>DM</span><span>ST</span></div><div><strong>Где возможности встречаются с целью</strong><small>Для бизнеса и студенческих команд</small></div></div></div><div className="hero-visual"><div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/><div className="floating-chip chip-top"><Sparkles size={16}/> Создание задач с помощью ИИ</div><div className="preview-card"><div className="preview-top"><span className="preview-icon"><Target size={23}/></span><span className="preview-kicker">РЕКОМЕНДОВАННАЯ ЗАДАЧА</span><ArrowUpRight size={17}/></div><h3>Сделаем работу склада эффективнее</h3><p>Поможем растущей торговой сети прогнозировать спрос и избегать дефицита товаров.</p><div className="preview-rule"/><div className="preview-bottom"><Badge score={95}/><span><strong>95</strong> / 100</span></div></div><div className="floating-chip chip-bottom"><span className="chip-check"><Check size={14}/></span> Готова к отличным идеям</div></div></div><div className="home-bottom"><div className="section-head"><div><span className="overline">ИССЛЕДУЙТЕ ВОЗМОЖНОСТИ</span><h2>Реальные задачи. Реальный результат.</h2></div><button className="text-link" onClick={()=>navigate('catalog')}>Все задачи <ArrowRight size={17}/></button></div><div className="featured-grid">{tasks.filter(isPublished).slice(0,3).map(t=><TaskTile key={t.id} task={t} open={()=>navigate('details',t.id)}/>)}</div></div></main>}
  {page==='catalog'&&<main className="container page enter"><div className="page-title-row"><div><span className="overline">ДОСКА ВОЗМОЖНОСТЕЙ</span><h1>Исследуйте задачи<span className="accent-dot">.</span></h1><p>Найдите реальную задачу, которую стоит решить.</p></div>{mode==='business'&&<button className="button primary" onClick={begin}><Plus size={18}/> Создать задачу</button>}</div><div className="catalog-toolbar"><div className="toolbar-label"><LayoutGrid size={18}/> {loading?'Загрузка...':`${list.length} задач`}</div><div className="filter-group"><label><SlidersHorizontal size={16}/><select value={topic} onChange={e=>setTopic(e.target.value)} aria-label="Фильтр по теме">{topics.map(v=><option key={v} value={v}>{topicLabel(v)}</option>)}</select><ChevronDown size={14}/></label><label><select value={level} onChange={e=>setLevel(e.target.value)} aria-label="Фильтр по готовности">{['All levels','Draft','Working','Ready','Priority'].map(v=><option key={v} value={v}>{readinessFilterLabel(v)}</option>)}</select><ChevronDown size={14}/></label><label><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Сортировка по рейтингу">{['Highest rated','Lowest rated'].map(v=><option key={v} value={v}>{v==='Highest rated'?'Сначала высокий рейтинг':'Сначала низкий рейтинг'}</option>)}</select><ChevronDown size={14}/></label></div></div>{loading?<div className="empty"><Search size={32}/><h3>Загрузка задач</h3><p>Подключаемся к каталогу задач.</p></div>:list.length?<div className="catalog-grid">{list.map(t=><TaskTile key={t.id} task={t} open={()=>navigate('details',t.id)}/>)}</div>:<div className="empty"><Search size={32}/><h3>Задачи не найдены</h3><p>Попробуйте изменить тему или уровень готовности.</p><button className="button subtle" onClick={()=>{setTopic('All topics');setLevel('All levels')}}>Сбросить фильтры</button></div>}</main>}
  {page==='create'&&<main className="container page enter"><div className="back-link"><button onClick={()=>navigate('home')}><ArrowLeft size={16}/> Вернуться к обзору</button></div><div className="builder-heading"><div><span className="overline">РАБОЧЕЕ ПРОСТРАНСТВО БИЗНЕСА</span><h1>Создать задачу<span className="accent-dot">.</span></h1><p>Начните с того, что уже знаете. Мы поможем оформить остальное.</p></div><div className="stepper"><span className={step>=0?'step-active':''}>01 <b>Описание</b></span><i/><span className={step>=1?'step-active':''}>02 <b>Уточнение</b></span><i/><span className={step>=2?'step-active':''}>03 <b>Доработка</b></span></div></div>
    {step===0&&<div className="builder-start"><div className="form-surface"><div className="surface-icon"><Sparkles size={21}/></div><h2>С какой задачей вы столкнулись?</h2><p>Опишите её своими словами. Идеальная формулировка не требуется.</p><label className="field-label" htmlFor="description">НАЧАЛЬНОЕ ОПИСАНИЕ</label><textarea id="description" className="input big-input" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Например: нам нужен удобный способ управлять складом и отслеживать запасы..."/><label className="field-label" htmlFor="create-topic">ТЕМА <small>(необязательно)</small></label><input id="create-topic" className="input" value={createTopic} onChange={e=>setCreateTopic(e.target.value)} placeholder="например, логистика"/><div className="form-bottom"><span><ShieldCheck size={16}/> Черновик виден только вам до публикации</span><button className="button primary" disabled={busy} onClick={analyze}>{busy?'Анализируем...':'Проанализировать задачу'} <ArrowRight size={18}/></button></div></div><div className="helper-surface"><div className="helper-symbol"><Lightbulb size={21}/></div><h3>Хорошие задачи начинаются с простого.</h3><p>Опишите проблему вашего бизнеса. Пошаговый процесс поможет заполнить пробелы и сделать задачу понятной для студентов.</p><div className="helper-line"><CheckCircle2 size={16}/> Техническое задание не требуется</div><div className="helper-line"><CheckCircle2 size={16}/> Займёт около двух минут</div></div></div>}
    {step===1&&<div className="questions-layout"><div className="form-surface"><div className="surface-icon"><Sparkles size={21}/></div><h2>Сделаем описание понятнее.</h2><p>Ответьте на три коротких вопроса, чтобы превратить идею в понятное описание.</p>{aiMode&&<div className="muted small ai-mode-note">{aiModeLabel(aiMode)}. Проверьте результат и при необходимости дополните его вручную.</div>}{questionList.map((q,i)=><label key={q} className="question-block"><span className="question-number">0{i+1}</span><strong>{q}</strong><textarea className="input" value={answers[i]} onChange={e=>setAnswers(old=>old.map((v,j)=>j===i?e.target.value:v))} placeholder={['например: руководители склада и сотрудники отдела запасов','например: история продаж и таблицы текущих остатков','например: сократить дефицит товаров на 20%'][i]}/></label>)}<div className="form-bottom"><button className="button subtle" onClick={()=>setStep(0)}><ArrowLeft size={17}/> Назад</button><button className="button primary" disabled={busy} onClick={generate}>{busy?'Создаём карточку...':'Создать карточку задачи'} <Sparkles size={17}/></button></div></div><div className="quote-card"><span className="overline">С ЧЕГО ВЫ НАЧАЛИ</span><p>“{description}”</p><span className="quote-footer"><Sparkles size={16}/> Превращаем идеи в действия</span></div></div>}
    {step===2&&draft&&<div className="editor-layout"><div className="editor-column"><div className="editor-intro"><span className="eyebrow"><Sparkles size={15}/> ОФОРМЛЕННАЯ ЗАДАЧА</span><h2>Сделайте её своей.</h2><p>Каждая деталь помогает студенческой команде понять, как выглядит успех.</p>{aiMode&&<div className="muted small ai-mode-note">{aiModeLabel(aiMode)}. Проверьте результат и при необходимости дополните его вручную.</div>}</div><div className="editor-card"><div className="editor-card-top"><div className="surface-icon"><Layers3 size={21}/></div><div><h3>Детали задачи</h3><p>Сохраните изменения, чтобы пересчитать рейтинг.</p></div><Badge score={ratingInfo?.score??rating(draft)} level={ratingInfo?.level||draft.readiness_level}/></div><div className="editor-fields">{fields.map(([key,label,kind])=><label key={key} className={kind==='textarea'?'field full':'field'}><span>{label}</span>{kind==='textarea'?<textarea className="input" value={draft[key]||''} onChange={e=>editDraft({...draft,[key]:e.target.value})} placeholder={`Добавьте: ${label.toLowerCase()}...`}/>:<input className="input" value={draft[key]||''} onChange={e=>editDraft({...draft,[key]:e.target.value})} placeholder={`Добавьте: ${label.toLowerCase()}...`}/>}</label>)}</div><div className="editor-actions"><button className="button subtle" disabled={busy} onClick={saveDraft}>{busy?'Сохраняем...':'Сохранить изменения'}</button><div>{isConfirmed(draft)?<span className="confirmed-label"><CheckCircle2 size={17}/> Подтверждена</span>:<button className="button outline" disabled={busy} onClick={confirmDraft}><Check size={17}/> Подтвердить</button>}<button className="button primary" disabled={busy} onClick={publish}>Опубликовать задачу <ArrowUpRight size={17}/></button></div></div></div></div><RatingPanel task={draft} ratingInfo={ratingInfo} useMock={useMock}/></div>}
  </main>}
  {page==='details'&&task&&<main className="container page enter"><div className="back-link"><button onClick={()=>navigate('catalog')}><ArrowLeft size={16}/> Все задачи</button></div><div className="detail-header"><div><div className="detail-meta"><span className="topic-pill">{topicLabel(task.topic)}</span><Badge score={rating(task)}/></div><h1>{task.title}</h1><p>{task.need||task.context||'Новая задача ждёт отличных идей.'}</p></div><div className="detail-score"><strong>{rating(task)}</strong><span>/100</span><small>РЕЙТИНГ ГОТОВНОСТИ</small></div></div><div className="details-layout"><article className="detail-content"><div className="detail-content-head"><span className="surface-icon"><Layers3 size={20}/></span><div><h2>Задача</h2><p>Всё, что нужно знать перед началом работы.</p></div></div>{fields.filter(([key])=>key!=='title'&&key!=='topic').map(([key,label])=><div className="detail-section" key={key}><h3>{label}</h3><p>{task[key]||'Пока не указано.'}</p></div>)}</article><aside className="detail-side"><div className="side-card"><div className="side-icon"><Target size={22}/></div><h3>Готовы создать что-то важное?</h3><p>Предложите свой взгляд и покажите бизнесу, на что способна ваша команда.</p>{mode==='student'?<button className="button primary full-button" onClick={()=>navigate('proposal',task.id)}>Отправить предложение <ArrowRight size={17}/></button>:<button className="button primary full-button" onClick={()=>navigate('proposals',task.id)}>Посмотреть предложения <ArrowRight size={17}/></button>}</div><div className="side-note"><ShieldCheck size={17}/> Реальные задачи от реального бизнеса.</div></aside></div></main>}
  {page==='proposal'&&task&&<main className="container page enter narrow"><div className="back-link"><button onClick={()=>navigate('details',task.id)}><ArrowLeft size={16}/> Вернуться к задаче</button></div><span className="overline">ВАШЕ ПРЕДЛОЖЕНИЕ</span><h1>Воплотите свою идею<span className="accent-dot">.</span></h1><p className="page-lead">Вы откликаетесь на задачу <strong>{task.title}</strong>. Расскажите бизнесу, как ваша команда решит её.</p><form className="form-surface proposal-form" onSubmit={submitProposal}><label className="field"><span>Идентификатор команды</span><input className="input" required type="number" min="1" value={proposalForm.team_id} onChange={e=>setProposalForm({...proposalForm,team_id:e.target.value})} placeholder="Идентификатор демонстрационной команды"/></label><label className="field"><span>Ваша идея</span><textarea className="input" required value={proposalForm.idea} onChange={e=>setProposalForm({...proposalForm,idea:e.target.value})} placeholder="Какое решение вы предлагаете?"/></label><label className="field"><span>План действий</span><textarea className="input" required value={proposalForm.plan} onChange={e=>setProposalForm({...proposalForm,plan:e.target.value})} placeholder="Какие шаги вы предпримете?"/></label><div className="form-pair"><label className="field"><span>Планируемый срок</span><input className="input" type="date" required value={proposalForm.deadline} onChange={e=>setProposalForm({...proposalForm,deadline:e.target.value})}/></label><label className="field"><span>Ссылка на прототип</span><input className="input" type="url" required value={proposalForm.prototype_url} onChange={e=>setProposalForm({...proposalForm,prototype_url:e.target.value})} placeholder="https://..."/></label></div><div className="form-bottom"><span><ShieldCheck size={16}/> Для отправки нужны все поля предложения.</span><button className="button primary" disabled={busy} type="submit">Отправить предложение <Send size={17}/></button></div></form></main>}
  {page==='proposals'&&task&&<main className="container page enter"><div className="back-link"><button onClick={()=>navigate('details',task.id)}><ArrowLeft size={16}/> Вернуться к задаче</button></div><span className="overline">РАБОЧЕЕ ПРОСТРАНСТВО БИЗНЕСА</span><h1>Предложения команд<span className="accent-dot">.</span></h1><p className="page-lead">Идеи для задачи <strong>{task.title}</strong>.</p>{proposals.filter(p=>String(p.task_id)===String(task.id)).length?proposals.filter(p=>String(p.task_id)===String(task.id)).map(p=><article className="proposal-card" key={p.id}><div className="proposal-top"><div className="team-icon"><GraduationCap size={21}/></div><div><span className="overline">СТУДЕНЧЕСКАЯ КОМАНДА</span><h2>Команда #{p.team_id}</h2></div><span className={'status '+p.status}>{proposalStatusLabel(p.status)}</span></div><div className="proposal-body"><div><h3>Идея</h3><p>{p.idea}</p></div><div><h3>План действий</h3><p>{p.plan}</p></div></div><div className="proposal-foot"><span><Clock3 size={16}/> {p.deadline}</span>{p.prototype_url&&<a href={p.prototype_url} target="_blank" rel="noreferrer">Открыть прототип <ExternalLink size={15}/></a>}<div className="proposal-actions"><button className="button outline" onClick={()=>changeStatus(p.id,'rejected')} disabled={p.status!=='pending'}>Отклонить</button><button className="button primary" onClick={()=>changeStatus(p.id,'accepted')} disabled={p.status!=='pending'}><Check size={16}/> Принять</button></div></div></article>):<div className="empty"><GraduationCap size={32}/><h3>Предложений пока нет</h3><p>После откликов студенческих команд их идеи появятся здесь.</p><button className="button subtle" onClick={()=>navigate('catalog')}>Каталог задач <ArrowRight size={16}/></button></div>}</main>}
  <footer className="footer container"><Logo onClick={()=>navigate('home')}/><span>Идеи, которые меняют мир. © 2026 Alem.</span><button onClick={()=>navigate('catalog')}>Исследуйте задачи <ArrowUpRight size={15}/></button></footer>{notice&&<div className="toast" role="status"><CheckCircle2 size={18}/>{notice}</div>}</div>
}
function TaskTile({task,open}){const score=rating(task);return <button className="task-tile" onClick={open}><div className="tile-top"><span className="topic-pill">{topicLabel(task.topic)}</span><ArrowUpRight className="tile-arrow" size={19}/></div><div className="tile-body"><h3>{task.title}</h3><p>{task.need||task.context||'Новая задача ищет студенческую команду.'}</p></div><div className="tile-bottom"><Badge score={score}/><span className="tile-score"><strong>{score}</strong><small>/100</small></span></div><div className="tile-progress"><span style={{width:`${score}%`}}/></div></button>}
export default App;
